# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 02:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0058_auto_20160317_0246'),
        ('personas', '0058_auto_20160205_0242'),
    ]

    operations = [
    ]
