# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 02:02
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0059_merge_20161220_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='content_images/nothing.jpg', upload_to='content_images/%Y/%m/%d/%H_%M_%S'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='profile_images/shadow_figure.jpeg', upload_to='story_images/%Y/%m/%d/%H_%M_%S'),
        ),
        migrations.AlterField(
            model_name='storyobject',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='profile_images/shadow_figure.jpeg', upload_to='profile_images/%Y/%m/%d/%H_%M_%S'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='profile_images/shadow_figure.jpeg', upload_to='user_images/%Y/%m/%d'),
        ),
    ]
